### ISSUE TITLE
Files getting locked

### ISSUE THREAD

**Issue by ullmark** [kamsar/Dianoga#1]
Hi there,
We are trying out this plugin but we're having an issue while running this in our CI environment. It seems that after being used, the plugin never releases the "OptimizePngDll". 

So our CI environment says this while trying to deploy the code. 

```
The process cannot access the file '...Website\Dianoga Tools\PNGOptimizer\PngOptimizerDll.dll' because it is being used by another process.
```

Do you have any suggestions here? Is that to be expected and we should make sure to run something like IISReset or is this a bug in the module.

Thanks!

**Comment by kamsar** [comment]
I have not run across this issue before and I'm doing CI deploys with it. But neither am I any P/Invoke expert so it could conceivably be a bug.

Are you copying the file always or only when it is changed?

**Comment by ullmark** [comment]
Hey,
Yes, the CI is copying the file always. To try to solve it now, we addded an IISreset as a first step of the deploy process. Seems to solve the problem and since the dlls are replaced anyways. It shouldn't be a problem. But I wonder if there is a leak..  

Maybe we could use more `using` around the streams, make sure they are disposed and closed correctly.

**Comment by kamsar** [comment]
It's not a leak, using [DllImport] causes a lock. In vNext I switched to dynamically loading and unloading the DLL as needed, thus freeing the lock on it unless an active optimization is in progress.
