### ISSUE TITLE
JPEG XL Support

### ISSUE THREAD

**Issue by Antonytm** [kamsar/Dianoga#101]
JPEG XL image format 

A modern image format optimized for web environments. JPEG XL generally has better compression than WebP, JPEG, PNG and GIF and is designed to supersede them. JPEG XL competes with AVIF which has similar compression quality but fewer features overall.

References:
https://github.com/libjxl/libjxl
https://caniuse.com/jpegxl

**Comment by markgibbons25** [comment]
Support added in 6.0.0-beta.1
