### ISSUE TITLE
JPEG 2000 Support

### ISSUE THREAD

**Issue by Antonytm** [kamsar/Dianoga#102]
Safari browsers have a big part of the market.

It looks like Safari doesn't have plans to support either Avif or JPEG XL.
But Safari supports JPEG 2000, which is a competitor of  Avif and JPEG XL.

References:
https://caniuse.com/?search=JPEG2000
https://github.com/uclouvain/openjpeg

**Comment by markgibbons25** [comment]
Newer versions of safari support WebP, so I dont see too much value in JPEG 2000. But will be led by community popularity.
