### ISSUE TITLE
Different assembly between NuGet and GitHub

### ISSUE THREAD

**Issue by orna91** [kamsar/Dianoga#108]
Adding Dianoga to my project via NuGet, I get the following error when starting Sitecore: "_Message: Could not resolve type name: Dianoga.NextGenFormats.WebP.WebPThumbnailGenerator, Dianoga (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName (XmlNode configNode, String [] parameters, Boolean assert))._ " Decompiling the Dianoga.dll obtained from NuGet I noticed that there is no **NextGenFormats** namespace. By downloading the project from GitHub the namespace is present.

I attach the screenshot of the decompiled Dianoga.dll.
Can you verify that dll has been loaded on NuGet?

Thank you

### Version of Dianoga ###
5.4.1.0

![Dianoga-NuGet-Decompile-dll](https://user-images.githubusercontent.com/53427411/154708953-f32f6c6d-186c-4238-981b-a45e17a2af59.jpg)
![Dianoga-NuGet](https://user-images.githubusercontent.com/53427411/154708957-84ba5301-423d-4764-ac0e-ee7970146100.jpg)

**Comment by markgibbons25** [comment]
Dianoga.NextGenFormats only is in the 6.x release, if you're looking at the readme on master branch then its actually for the 6.x, you can switch to the tag for the release you are on to get the right readme. 
That said, I'd encourage you to try 6.x, I don't forsee any more changes going into that release.
