### ISSUE TITLE
webp content-type not returned when CDN enabled

### ISSUE THREAD

**Issue by kwyc** [kamsar/Dianoga#110]
### Version of Dianoga ###
5.2.0 

### Environment description ###
Production Sitecore 9.3

### What configs you have enabled ###
Production CD:

> Dianoga.DisableForSites.config
> Dianoga.Jpeg.config
> Dianoga.Png.config
> Dianoga.Strategy.GetMediaStreamSync.config
> Dianoga.WebP.CDN.config
> Dianoga.WebP.config

Production CM:

> Dianoga.DisableForSites.config
> Dianoga.Jpeg.config
> Dianoga.Png.config
> Dianoga.Strategy.MediaCacheAsync.config
> Dianoga.WebP.config

### Reproducible steps (1... 2... 3...) that cause the issue ###
Load CDN site vs non-CDN site and check content-type on .webp images. Expect image/webp instead of image/jpeg.

### What you expected to see, versus what you actually saw ###

On CD, when CDN is enabled, 
![image](https://user-images.githubusercontent.com/9687298/164784232-512bd12f-5d1d-48c6-9f06-def4dcae08a7.png)
Expected to see image/webp instead of image/jpeg.

On CM, when CDN is disabled,
![image](https://user-images.githubusercontent.com/9687298/164784194-b2abe431-a5ba-496e-afdf-8f6fef137672.png)
image/webp is returned which is correct behaviour.

GenerateCacheKey orders seems correct.
<processor type="Sitecore.Mvc.Pipelines.Response.RenderRendering.GenerateCacheKey, Sitecore.Mvc" resolve="true"/>
<processor type="Dianoga.WebP.Pipelines.GenerateCacheKey, Dianoga" patch:source="Dianoga.WebP.CDN.config"/>

### Relevant logs ###
N/A

Also is latest Dianoga 5.4.1 compatible with Sitecore 9.3?

**Comment by markgibbons25** [comment]
You need to be on at least 5.3, but I'd recommend trying the 6.0 release. All compatible with Sitecore 9.3

**Comment by kwyc** [comment]
Thank you, we will give 6.0 a try!

**Comment by kwyc** [comment]
@markgibbons25 

Hi Mark, we have upgraded from V5 to 6; however, the issue with CDN still persists after enabling "Dianoga.NextGenFormats.CDN.config", where images return now have "?extension" appended after them and the header still shows image/jpg where we expect image/webp.

Network:
../hp_hero_spring.jpg?extension=
../ic_art_moves.png?extension

Since we don't want "?extension" to appear, we have temporarily commented off the "mediaLibrary" node within "Dianoga.NextGenFormats.CDN.config" so the extension query string is not added.

Commented off,
		<mediaLibrary>
			
			<mediaProvider
				type="Dianoga.NextGenFormats.MediaProvider, Dianoga"
				patch:instead="mediaProvider[@type='Sitecore.Resources.Media.MediaProvider, Sitecore.Kernel']"/>
		</mediaLibrary>

Which means we are back to square one (before V6 upgrade), where "image/webp" header is not returned when CD URL is behind CDN. CM URL is fine as it is not behind CDN, so "image/webp" header is returned correctly. Do you have any other recommendations to take?

Thanks!
