### ISSUE TITLE
WebP image not getting generated from CDN

### ISSUE THREAD

**Issue by NStrongin** [kamsar/Dianoga#112]
**Version of Dianoga**
5.4.1

**Environment description**
Sitecore.NET 9.3.0
.NET Framework 4.7.2

**What configs you have enabled**
Dianoga.DisableForSites.config
Dianoga.Jpeg.config
Dianoga.Log.config
Dianoga.Png.config
Dianoga.Svg.config
Dianoga.WebP.CDN.config
Dianoga.WebP.config

**Web.config changes:** 
I`ve replaced in _**sitecore_media.ashx**_ type to "Dianoga.MediaRequestHandler, Dianoga" name="Sitecore.MediaRequestHandler" 

**What you expected to see, versus what you actually saw**
**Expected:** To see images being pulled down in webp format
**Actual:** Images are received in optimized formats (jpeg, png, etc), but not in webp.

**Logs files:**
All logs files are empty.

**Comments**
After deploy on CD in Azure MediaProvider adds extension webp as a URL param. This should trigger the webp optimizer in the MediaRequestHandler. But the MediaProvider doesn’t appear to run. On my local envirement I don`t use CDN and Dianoga works fine. And I am probably missing something?

**Comment by markgibbons25** [comment]
It sounds like an environment issue so I would recommend asking in Sitecore Slack to get help.

**Comment by Antonytm** [comment]
@NStrongin 

Do you have Dianoga.WebP.CDN.config enabled locally and everything is fine?
(ignore that you are not under CDN)

**Only if works locally with Dianoga.WebP.CDN.config enabled:**
Can you try to clean mediaCache folder on server?
You may have cache files and keys that prevents new files to be generated.

**Comment by NStrongin** [comment]
@Antonytm 

We cleared the mediaCache folder on the server after adding Dianoga.

**Comment by markgibbons25** [comment]
For Azure CDN support you'll need to upgrade to 6.1.0 and review the readme config for this.
