### ISSUE TITLE
Error in logs for Dianoga JPEG lossless optimization

### ISSUE THREAD

**Issue by swthp** [kamsar/Dianoga#114]
### Dev, QA  ###

###Config files enabled -  Dianoga.DisableForSites.config, Dianoga.Jpeg.config , Dianoga.Log.config, Dianoga.Png.config, Dianoga.Svg.config Dianoga.Strategy.GetMediaStreamSync,  ###

### The image loads fine but there is error in the logs - 
ERROR Dianoga: Unable to optimize ["Image path"] due to a processing error! It will be unchanged.
Exception: System.InvalidOperationException
Message: "~\App_Data\Dianoga Tools\mozjpeg\jpegtran.exe -progressive -outfile "C:\windows\TEMP\tmp9CE3.tmp" "C:\windows\TEMP\tmp9CE1.tmp"" exited with unexpected exit code 1. ###

**Comment by markgibbons25** [comment]
It means mozjpeg was unable to convert it. Possibly as its not a jpeg or its corrupted.
