### ISSUE TITLE
Move Dianoga files to /App_Config/Modules/

### ISSUE THREAD

**Issue by gilbertaoe** [kamsar/Dianoga#120]
This isn't exactly a bug, but I wasn't able to request features/enhancements.

Sitecore has had the modules folder available for non-custom/3rd-party config files that loads directly before the include folder. I'm not sure when they added this but ever since version 9.3, SXA has been installing their config files into the modules folder, allowing the custom includes folder to be less messy and to be purely "custom overrides". For modules like Unicorn or SXA, this reduces the need for hackly folder or file names such as zzz.example.config or zzz.Feature.Overrides

In all my Sitecore projects, I will typically manually move the Dianoga config folder to /App_Config/Modules, so I thought I'd try requesting the change so I don't need to anymore.

I've already forked and made the changes in a pull request if that helps explain my request. I'll link it down below. And if you end up not wanting these changes no worries, I was just feeling a bit bored today :p

**Comment by gilbertaoe** [comment]
Here's the pull request: https://github.com/kamsar/Dianoga/pull/121

**Comment by markgibbons25** [comment]
I also manually move Dianoga and Unicorn etc to Modules. Problem with doing it here is it breaks Sitecore 8 compatibility. It was briefly discussed for Unicorn here https://github.com/SitecoreUnicorn/Unicorn/pull/320
I know a lot of Sitecore 8 solutions still use this, and those customers tend to not have a CDN so rely on this module. @Antonytm thoughts?

**Comment by Antonytm** [comment]
Dianoga is not an official Sitecore module. It is a community-driven module.

According to the official Sitecore Configuration Layers Definition:
`Modules` - [Reserved for Sitecore use. Contains configuration files for official Sitecore modules, such as Web Forms for Marketers.](https://doc.sitecore.com/xp/en/developers/90/platform-administration-and-architecture/configuration-layers.html)

P.S. I also intuitively think, that the modules folder should be for all modules. But let's follow official documentation to avoid confusion.

**Comment by gilbertaoe** [comment]
@Antonytm ya that makes sense, I didn't realize it was specifically reserved for Sitecore official modules. Thanks!
