### ISSUE TITLE
Dianoga (Version - 6.1.0) conversion to WebP not working in production servers?

### ISSUE THREAD

**Issue by AswathyJagadees** [kamsar/Dianoga#127]
I have installed dianoga for my website to ensure the images are compressing to Webp. 
Steps I have done:-
1)Install the latest release of the Dianoga NuGet Package over the Foundation project. (Version - 6.1.0)
2)Copy the Dianoga Tools folder to the App_Data folder of your website.
3)Copy Default Config Files/*.config to App_Config\Include\Dianoga.
4)Reference Dianoga.dll  and System.Threading.Tasks.Dataflow.dll or the source project in your web project
5)1.	Open web.config and change line (I am using Sitecore SXA)
<add verb="*" path="sitecore_media.ashx" type="Sitecore.Resources.Media.MediaRequestHandler, Sitecore.Kernel" name="Sitecore.MediaRequestHandler" />
to
<add verb="*" path="sitecore_media.ashx" type="Dianoga.NextGenFormats.MediaRequestHandlerXA, Dianoga" name="Sitecore.MediaRequestHandler" />
OR if you have a custom MediaRequestHandler then you need to make some changes - see MediaRequestHandler.cs
6)Create a project in your Foundation layer for Dianoga.
7)The installation will add the required files to the Project.
8)Now, Publish the project to your Sitecore Instance.
9)Open the path Sitecore-webroot/App_Data/MediaCache in File Explorer and empty that folder.
10)Restart your Sitecore instance on IIS.
11)Dianoga should now be configured on your site.
12)Open the C:\inetpub\wwwroot\sc93sc.dev.local\App_Data\logs folder to check whether the Dianoga log is created.

After doing the above process Dianoga WebP conversion is happening successfully in QA,UAT and Production CM server. The conversion is not happening only in Production CD servers which is serving the public global site.

The below Dianoga configs I have enabled. Kindly have a look.
![image](https://user-images.githubusercontent.com/124549605/216886999-986da7af-2452-4e41-aebb-94c18afba38c.png)
<img width="950" alt="Conversion not happening to WEBP for Production CD Server" src="https://user-images.githubusercontent.com/124549605/216888095-2f638248-af3a-4028-86ce-e6021800ac4b.PNG">

This is a critical issue and its not working in the global site. Looking for quick update from Dianoga team.
@kamsar @molnarm

**Comment by molnarm** [comment]
I don't know why I got tagged here, Dianoga is the work of @kamsar.

**Comment by AswathyJagadees** [comment]
Hi @kamsar ,

Please provide an update on this high priority issue. We are awaiting for your response to go ahead.

Regards
Aswathy

**Comment by michaellwest** [comment]
> Hi @kamsar ,
> 
> Please provide an update on this high priority issue. We are awaiting for your response to go ahead.
> 
> Regards
> Aswathy

Hi @AswathyJagadees this is an open source project maintained for free. Are you offering to pay for additional support or perhaps submit a pull request in which the "issue" is addressed by you and your organization?
