### ISSUE TITLE
Dianoga error in Sitecore instance

### ISSUE THREAD

**Issue by Kumar722** [kamsar/Dianoga#128]
Server Error in '/' Application.
Could not load type 'Dianoga.MediaRequestHandler' from assembly 'Dianoga'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.TypeLoadException: Could not load type 'Dianoga.MediaRequestHandler' from assembly 'Dianoga'.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[TypeLoadException: Could not load type 'Dianoga.MediaRequestHandler' from assembly 'Dianoga'.]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +95
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +64
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +59
   System.Web.Configuration.HandlerFactoryCache.GetTypeWithAssert(String type) +51
   System.Web.Configuration.HandlerFactoryCache.GetHandlerType(String type) +17
   System.Web.Configuration.HandlerFactoryCache..ctor(String type) +25
   System.Web.HttpApplication.GetFactory(String type) +98
   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +499
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +131

I have the latest version package installed in the code and the configs are updated, I'm receiving the above error when trying to select any image in the sitecore instance after updating the web.config to support webp Dianoga,  using the below link as reference 
https://www.vinayjadav.com/posts/webp-for-sitecore-with-dianoga

**Comment by Kumar722** [comment]
@kamsar Could you please help us with the above situation

**Comment by markgibbons25** [comment]
Please ask for troubleshooting help here https://sitecore.chat/

**Comment by jansevcik** [comment]
`<add verb="*" path="sitecore_media.ashx" type="Dianoga.NextGenFormats.MediaRequestHandler, Dianoga" name="Sitecore.MediaRequestHandler" />`
