### ISSUE TITLE
Add optional -progressive parameter

### ISSUE THREAD

**Issue by EarlofArgyle** [kamsar/Dianoga#13]
Hi,

is it possible to add "**-progressive**" (or other parameters for jpegtran) as an option to the command line parameters, which can be set via the XML Config? 

Best regards
David

**Comment by kamsar** [comment]
You're welcome to contribute that addition. See https://github.com/kamsar/Dianoga/blob/3.0/src/Dianoga/Optimizers/Pipelines/DianogaJpeg/MozJpegOptimizer.cs

This is loaded via the [Sitecore Factory](http://sitecore-community.github.io/docs/documentation/Sitecore%20Fundamentals/Sitecore%20Configuration%20Factory/) here, so parameters could be mapped as properties: https://github.com/kamsar/Dianoga/blob/3.0/src/Dianoga/Default%20Config%20Files/Dianoga.Jpeg.config#L25

**Comment by victorantos** [comment]
Will this PR solve the above issue?
https://github.com/kamsar/Dianoga/pull/17

**Comment by kamsar** [comment]
"Probably" :)

**Comment by kamsar** [comment]
@victorantos' PR to add this is in 3.0.3-beta01 for testing. Give it a shot!

**Comment by kamsar** [comment]
This is fixed in 3.1
