### ISSUE TITLE
Lot of temp files getting created on the server for PNG Optimizer

### ISSUE THREAD

**Issue by KunalGanatra** [kamsar/Dianoga#14]
I am facing an issue where the C:\Windows\Temp folder on the server is getting loaded with temp files being created by PNG Optimizer. It seems they work fine for JPEGOptimizer. Looking at the code trough disassembler , it seems there isnt a proper disposition of these files. Can you please review.

**Comment by KunalGanatra** [comment]
Hey Team, It is a critical issue for us. Can you please have a look?

FileName: PngOptimizer.cs
MethodName: GetOrLoadPngOptimizer
Line: var tempPath = Path.GetTempFileName();

The temp file getting generated is not disposed.

**Comment by KunalGanatra** [comment]
Thank you @patocl.. Just waiting for @kamsar  to pull the request

**Comment by kamsar** [comment]
Closing this in favor of #15

**Comment by kamsar** [comment]
This has been fixed in 3.0.2
