### ISSUE TITLE
Dianoga error

### ISSUE THREAD

**Issue by danieljuvito** [kamsar/Dianoga#21]
Could not resolve type name: Dianoga.Invokers.MediaCacheAsync.Pipelines.Initialize.MediaCacheReplacer, Dianoga (method: Sitecore.Configuration.Factory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

**Comment by danieljuvito** [comment]
It works like a charm when i use version 2.0.2

**Comment by kamsar** [comment]
Sounds like either the config or the assembly does not match the version being deployed.

**Comment by estockwell-alpert** [comment]
I have this issue as well. How would I fix the config/assembly version?

**Comment by estockwell-alpert** [comment]
I tried changing the version in Nuget but cannot resolve this error.

**Comment by kamsar** [comment]
See #22
