### ISSUE TITLE
Runtime Error: Cannot resolve MediaCacheReplacer

### ISSUE THREAD

**Issue by estockwell-alpert** [kamsar/Dianoga#22]
I installed Dianoga from Nuget. I selected version 3.1.1. My project builds, but when I try to load my site I get the runtime error "Could not resolve type name: Dianoga.Invokers.MediaCacheAsync.Pipelines.Initialize.MediaCacheReplacer."

**Comment by kamsar** [comment]
There's a good chance your project isn't targeting .NET >= 4.5.2. If you upgrade the target framework and reinstall the nuget package, it will probably work.

For some reason nuget skips assemblies when the framework version is too low. 4.5.2 is necessary for the package to maintain compatibility with Sitecore 8.2.x.

**Comment by estockwell-alpert** [comment]
Ah, you're right, my project was using 4.0. Thanks!
