### ISSUE TITLE
Entire App_Data is included in project when installing via NuGet

### ISSUE THREAD

**Issue by nerfpops** [kamsar/Dianoga#25]
Thanks for creating excellent tools for Sitecore. Both this and your branch data source-library have spared me many hours of work.

As the title suggests, I'd like to not include the entire App_Data folder when installing. I believe none of the installed App_Data files should be visible in the project. MediaCache is also included causing the installation to take quite a while.

Is it possible to remove this behavior?

**Comment by kamsar** [comment]
The package will add the `App_Data/Dianoga Tools` folder to the project (that's the only reliable way I've found to get the supporting files to be deployed), but should not affect any items that are not coming from the NuGet package. Are you using any custom include/exclude language (wildcards, perhaps) in your csproj that might confuse NuGet?

FWIW, I have never seen this behaviour before.

**Comment by nerfpops** [comment]
Not using any include/exclude language. Just tried installing it again and the entire App_Data is included.

**Comment by nerfpops** [comment]
By looking at your nuspec, it must be a NuGet-thing to recursively include all files in the folder you're placing the tools. Would it make sense to put the tools somewhere else, perhaps in the root? App_Data is not included in our project, so having another folder like Dianoga Tools, which probably should be included when publishing, placed in the root, would actually be better in our case.

It's not that big of a deal and everything else seems to Just Work, but in a multi developer env it's a bit cumbersome having to remove the included files, which takes quite some time, even when deleting cached media, logs and diagnostics before installing.

**Comment by nerfpops** [comment]
On second thought: I'll just find something to include from App_Config, like the license, and the problem goes away. Closing.

**Comment by markgibbons25** [comment]
Hi @kamsar I am also running into this issue - basically we don't want to check all the Dianoga Tools into source control (17MB of binaries is a tough ask). Is the solution here an option? https://stackoverflow.com/a/30386836/1102452

**Comment by kamsar** [comment]
There's nothing magical about the tools folder being committed or included in the project, it just needs deploying. Feel free to remove it after installing the Nuget package and deploying it some other way. 




Though 17mb of bins also is not going to kill SCM and will be an easier solution overall  




On Mon, Feb 12, 2018 at 6:11 PM -0800, "Mark Gibbons" <notifications@github.com> wrote:












Hi @kamsar I am also running into this issue - basically we don't want to check all the Dianoga Tools into source control (17MB of binaries is a tough ask). Is the solution here an option? https://stackoverflow.com/a/30386836/1102452

**Comment by markgibbons25** [comment]
I think that I'm not alone in saying that as devs we don't like to check in binaries if it can be avioded ;)
On that note, using the example in the link previously, I came up with my own solution:

1. Install the Dianoga nuget package
2. Delete all the App_Data files
3. Create a file called Dianoga.targets with the following and adjust based on your relative directories
`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <NativeLibs Include="$(MSBuildThisFileDirectory)..\..\..\..\packages\Dianoga.3.1.1\content\App_Data\Dianoga Tools\**\**" />
        <None Include="@(NativeLibs)">
            <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <NativeLibs Include="$(MSBuildThisFileDirectory)..\..\..\..\packages\nQuant.1.0.3\Tools\net40\**\**" />
        <None Include="@(NativeLibs)">
            <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>`
4. Add the following to your csproj file at the bottom:
`<Import Project="Dianoga.targets" Condition="Exists('Dianoga.targets')" />`
5. Modify the Dianoga configs to get the libaries from your /bin/ directory instead of /App_Data/
