### ISSUE TITLE
Sitecore XP 9.0 Update 1

### ISSUE THREAD

**Issue by devstack** [kamsar/Dianoga#31]
Is this module relevant / compatible with the latest version of Sitecore (as of now that is Sitecore XP 9.0 Update 1)

The reason for the question is that during the upgrade process from 8.1 we're receiving notifications about breaking code changes found in the Dianoga assemblies.

I tried to find Kam's email address online but to no avail :(

**Comment by kamsar** [comment]
It's relevant and ought to be compatible. What were the identified breaking changes?




On Tue, Jan 30, 2018 at 3:00 AM -0800, "devstack" <notifications@github.com> wrote:












Is this module relevant / compatible with the latest version of Sitecore (as of now that is Sitecore XP 9.0 Update 1)


The reason for the question is that during the upgrade process from 8.1 we're receiving notifications about breaking code changes found in the Dianoga assemblies.


I tried to find Kam's email address online but to no avail :(

**Comment by devstack** [comment]
[messages.txt](https://github.com/kamsar/Dianoga/files/1678123/messages.txt)
I've attached an XML file with the details.

**Comment by kamsar** [comment]
Interesting. Well, I have not tried it myself. If you've got the time to
give it a shot I'd be happy to hear how it goes and help with any necessary
cleanup.

**Comment by devstack** [comment]
Hi Kam, apologies if this is obvious, Are you suggesting that I try see if it works as is or recompile the source using the latest Sitecore dll's?

**Comment by kamsar** [comment]
Try it as is




On Thu, Feb 1, 2018 at 2:36 AM -0800, "devstack" <notifications@github.com> wrote:












Hi Kam, apologies if this is obvious, Are you suggesting that I try see if it works as is or recompile the source using the latest Sitecore dll's?

**Comment by devstack** [comment]
OK thanks, will do

**Comment by nemetos-nsl** [comment]
Great module! 
I have manually (as I was working on .Net 4.6.2) integrate it with Sitecore 9 Update 1 and it works just fine.
