### ISSUE TITLE
Dianoga doesn't fail gracefully when it can't create temp files

### ISSUE THREAD

**Issue by sebastianlay** [kamsar/Dianoga#35]
For some probably unrelated reason we had too many temp files which caused `Path.GetTempFileName();`  (used in https://github.com/kamsar/Dianoga/blob/3.0/src/Dianoga/Optimizers/CommandLineToolOptimizer.cs#L178) to fail with an IOException.
Unfortunately this led to Sitecore becoming almost unresponsive. It would be great if Dianoga would back off when too many of these calls fail.

**Comment by kamsar** [comment]
This is resolved in [4.0p1](https://github.com/kamsar/Dianoga/releases/tag/4.0-pre01)
