### ISSUE TITLE
When Using Path.GetTempFileName() Dianoga Does Not Cleanup Temp Files

### ISSUE THREAD

**Issue by nolivermke** [kamsar/Dianoga#36]
When optimizing PNGs specifically the extension of the TMP file is explicitly changed to .png from .tmp. 
When Dianoga attempts to cleanup after itself it only removes the *.png temp file but not the original file. 

Given a sufficient amount of optimized images eventually the temp file directory will grow to contain over 65,535 files causing Path.GetTempFileName() to throw an exception as referenced here [https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx) Both issue #32 and #35 reference the same error `Exception: System.IO.IOException Message: The file exists.`

**Relevant Code Snippets**
https://github.com/kamsar/Dianoga/blob/8308e589cddeb747be37c6f385b45895061a47a8/src/Dianoga/Optimizers/Pipelines/DianogaPng/PngOptimizer.cs#L16-L20

https://github.com/kamsar/Dianoga/blob/8308e589cddeb747be37c6f385b45895061a47a8/src/Dianoga/Optimizers/CommandLineToolOptimizer.cs#L91-L95

**Comment by kamsar** [comment]
This is resolved in [4.0p1](https://github.com/kamsar/Dianoga/releases/tag/4.0-pre01)
