### ISSUE TITLE
SVG is converted to WebP when a querystring is used in the URL

### ISSUE THREAD

**Issue by mquekel** [kamsar/Dianoga#43]
Hi, 

I am using Dianoga 4.0 with WebP support enabled.

When I request an SVG image that has a querystring. Dianoga is converting the image to WebP format and the image is broken. 

Example URL 
`-/media/public/support/cell-phone-icon.svg?la=en&mw=1300`

This results in a broken image.
![broken-image](https://user-images.githubusercontent.com/17524662/49160588-60511200-f327-11e8-971c-4ace5e136db8.PNG)

The image is converted correctly when it has no querystring.

**Comment by Antonytm** [comment]
Hello @mquekel 

Please, take a look on my commit 1ed6571. It should resolve issue with SVG images. I will test it and if everything is fine then I will add it as pull request to main stream.

**Comment by mquekel** [comment]
Great! thanks for the quick response.
For now I will disable WebP support until the next release of Dianoga.

**Comment by uioporqwerty** [comment]
Any updates on this @Antonytm? I'm also experiencing the same issue.

**Comment by Antonytm** [comment]
@uioporqwerty Pull request is waiting for approve

**Comment by kamsar** [comment]
Closing this; merged #45 and will push with a new release shortly.
