### ISSUE TITLE
Could not resolve the 'getMediaStream'

### ISSUE THREAD

**Issue by architguptaa** [kamsar/Dianoga#48]
Hello,

i have installed latest version of Dianoga  and on prod we are getting this error

Could not run the 'getMediaStream' pipeline for 'Image path'. Original media data will be used.

In the logs i am getting this exception:

Exception: System.Exception Message: Could not resolve type name: Dianoga.Invokers.GetMediaStreamSync.OptimizeImage, Dianoga (method: Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert)). Source: Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) at Sitecore.Diagnostics.Error.Raise(String error, String method) at Sitecore.Diagnostics.Error.Assert(Boolean condition, String error) at Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert) at Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, Boolean assert) at Sitecore.Pipelines.CorePipelineFactory.GetObjectFromType(XmlNode processorNode) at Sitecore.Pipelines.CorePipelineFactory.GetProcessorObject(XmlNode processorNode) at Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) at Sitecore.Resources.Media.Media.GetStreamFromPipeline(MediaOptions options, Boolean& canBeCached)

For the sitecore.diagnostic error the message is:

Could not resolve type name: Dianoga.Invokers.GetMediaStreamSync.OptimizeImage, Dianoga (method: Sitecore.Configuration.DefaultFactory.CreateType(XmlNode configNode, String[] parameters, Boolean assert)).

we have already copied dianogatools folder in root 

can you please help me in this?

**Comment by kamsar** [comment]
It sounds like Dianoga.dll is not in your bin folder. That type is valid, if it was present:

https://github.com/kamsar/Dianoga/blob/3.0/src/Dianoga/Invokers/GetMediaStreamSync/OptimizeImage.cs
