### ISSUE TITLE
SVG image is not displaying

### ISSUE THREAD

**Issue by rakeshbindal4** [kamsar/Dianoga#58]
Reproduction:

- Install Dianoga , enable WebP.config
- Upload an SVG image to the media library
- View the image on the frontend (ie. /-/media/aj.svg) in a WebP-supporting browser

I am using Dianoga with Sitecore 8.2 to optimize the images. It works fine for jpg, gif, png extension but it has issues with SVG images. Once we access the SVG image, dianoga works in the backend to optimize the image. I have verified this by checking the logs

### 38100 20:12:54 INFO Dianoga: optimized /Images/aj.svg [original size] (final size: 16372 bytes) - saved 116247 bytes / 87.65%. Optimized in 16448ms.

where it says that aj.svg is optimized by 87.65% and no error after that. It means SVG image is successfully optimized. Now if we try to refresh the webpage after clearing the browser cache. I am not able the see an optimized cache image.

To troubleshoot i followed the below steps

- Checked the media cache where i find the webp file is created
- I clicked on webp file it shows blank page 

So it seems that Dianoga is able to optimize the SVG image but failed to convert to webp.
![svg-error](https://user-images.githubusercontent.com/7020234/74426263-0d577200-4e7b-11ea-975b-35550cd881f9.PNG)

**Comment by markgibbons25** [comment]
Hi @rakeshbindal4 WebP does not support converting svg. I would urge you to try the latest 5.0 release which has updated the SVG library.

**Comment by markgibbons25** [comment]
I'm closing this please contact me if you would like it reopened
