### ISSUE TITLE
Poor Png optimization

### ISSUE THREAD

**Issue by verndalejcastillo** [kamsar/Dianoga#60]
Optimization resulting in < 15% improvement and sometimes 100% of the original file size (0 improvement). 

example below.

![image](https://user-images.githubusercontent.com/41742515/75361672-ab890600-5885-11ea-844a-2515ddf015e0.png)

We are using the defaults for all the configs.  When I manually use PngOptimizer, I get the same results so it doesn't appear to be an issue with the setup itself.  Has anyone written an integration with other optimizers?

Thanks

--

Original file:

![example-content-block-6](https://user-images.githubusercontent.com/41742515/75361601-914f2800-5885-11ea-91ab-05a4cd3c9f86.png)

**Comment by markgibbons25** [comment]
Hi @verndalejcastillo the latest 5.0 RC has a new PNG CLI optimizer using https://pngquant.org/ would you be able to try that and post the results?

**Comment by markgibbons25** [comment]
From my testing, pngquant CLI reduces it from 782KB to 304KB.
