### ISSUE TITLE
WebP not working on any CDN

### ISSUE THREAD

**Issue by markgibbons25** [kamsar/Dianoga#61]
This is because various CDN either don't pass the "Accept" header, or because they don't honour the "Vary: Accept" header.

A potential workaround is to have a unique query string parameter for image types and browsers that support WebP.

**Comment by markgibbons25** [comment]
I've experimented with having a unique query string parameter for image types and browsers that support WebP, but this falls flat with the HTML cache.

**Comment by markgibbons25** [comment]
In SXA, requests to the sxa/search/results api doesnt pass image/webp in accept types header.

**Comment by jeroendegroot** [comment]
Just found this after asking [this](https://sitecore.stackexchange.com/questions/30436/dianoga-v5-with-webp-cdn-and-sitecore-html-cache) question on SSE which I think might be related to this change. Are you able to explain what was changed as part of this fix, and can you opt out of it if your CDN supports "Accept" header? Thanks for all the great work on Dianoga this is making such a significant performance improvement!
