### ISSUE TITLE
Safari webp render Issue

### ISSUE THREAD

**Issue by beyondsun** [kamsar/Dianoga#64]
Hi,
I got latest 5.0.0 Release Candidate 6 and noticed that on safari when Request Accept headers does not have image/webp, image fails to fallback and does not render. (displays blank).
I guess it is to do with cache as when the first time if the image renders in webp supported browsers it caches to show webp images and being rendered as webp on non webp supported browsers too.

**Comment by markgibbons25** [comment]
Do you have a CDN? Have you checked the configs are all up to date as they have changes in newer rc's? Are you using sync or async strategy?

**Comment by beyondsun** [comment]
Thank you @markgibbons25 for your reply
- No CDN
- Yes have ensure configs are up to date 
- using Dianoga.Strategy.GetMediaStreamSync on CD
- using Dianoga.Strategy.MediaCacheAsync on CM

**Comment by markgibbons25** [comment]
Hi @beyondsun was this an upgrade from a previous Dianoga version? If so can you confirm if you cleared the media cache?

**Comment by markgibbons25** [comment]
I have spoken with @beyondsun and it was indeed an upgrade and clearing the media cache resolved it.
