### ISSUE TITLE
WebP files not generated with JSS

### ISSUE THREAD

**Issue by whuu** [kamsar/Dianoga#65]
It looks like v5 doesn't generate WebP files when used with Sitecore JSS.
I tried with rc5 and rc6.

With Dianoga.WebP.config enabled, I replaced JSS media handler in web.config:
`<add name="Sitecore.JavaScriptServices.Media.MediaRequestHandler" verb="*" path="sitecorejss_media.ashx" type="Sitecore.JavaScriptServices.Media.MediaRequestHandler, Sitecore.JavaScriptServices.Media" />`

with custom one:
```
using MediaRequestHandler = Sitecore.JavaScriptServices.Media.MediaRequestHandler;

    public class JSSWebPMediaHandler : MediaRequestHandler
    {
        protected override bool DoProcessRequest(HttpContext context, MediaRequest request, Media media)
        {
            if (context?.Request.AcceptTypes != null && context.Request.AcceptTypes.Contains("image/webp"))
            {
                request.Options.CustomOptions["extension"] = "webp";
            }
            return base.DoProcessRequest(context, request, media);
        }
    }
```

After clearing media cache folder, Dianoga generates compressed .png or .jpg files, but no .webp.
Version 4 actually does generate .webp files with JSS.

**Comment by markgibbons25** [comment]
I haven't tested this with jss as I am not familiar with it. But in principle it works by the request to the image needs to have accept webp header. Unless you have the CDN config enabled then it is the request to the page that renders the image url needs to have accept webp header.

**Comment by whuu** [comment]
You pointed me into right direction, after enabling `Dianoga.WebP.CDN.config` (even on local). WebP are generated with JSS and used on the page. Tested with v5 rc6.
Of course you need to overwrite jss media request handler as stated above.

**Comment by markgibbons25** [comment]
That's great news. Can you be sure to test on safari too that it falls back to original format?

**Comment by whuu** [comment]
I checked in IE content-type of response is png or jpg, so looks ok.
