### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by kamsar** [kamsar/Dianoga#7]
With SVGO or something.

* Include SVG mime type e.g. https://community.sitecore.net/developers/f/8/t/1670
* Add https://laubplusco.net/compress-svg-images-sitecore-media-library/ (permission granted)
* Prevent log errors e.g. https://jammykam.wordpress.com/2015/11/18/svg-in-media-library-polluting-log-files-with-errors/

**Comment by Saturate** [comment]
Would be a pretty neat feature, as we see more and more svg usage.

**Comment by kamsar** [comment]
Of note: https://jammykam.wordpress.com/2015/11/18/svg-in-media-library-polluting-log-files-with-errors/

**Comment by kamsar** [comment]
SVGO support, along with baseline SVG media and SVG gzipping, is in the latest 3.0 branch
