### ISSUE TITLE
Webp is not getting generated

### ISSUE THREAD

**Issue by AbhishekKumar26** [kamsar/Dianoga#71]
### Version of Dianoga ###
5.0.1
### Environment description ###
Sitecore 9.1 - Standalone
### What configs you have enabled ###

Dianoga.DisableForSites.config
Dianoga.Jpeg.config
Dianoga.Png.config
Dianoga.Strategy.MediaCacheAsync.config
Dianoga.WebP.CDN.config
### Reproducible steps (1... 2... 3...) that cause the issue ###
I have updated the media handler as mentioned in the documentation.
Images are getting optimized but **.webp** format is not getting generated. I checked inside the Media Cache.
Browser is sending the required attribute in the header.

I do see multiple versions of the jpeg image in media cache.
### What you expected to see, versus what you actually saw ###
I am expecting **webp** image to be returned.

### Relevant logs ###
No logs for Dianoga in the log file..

**Comment by AbhishekKumar26** [comment]
Hi Team,

While trying to make it work, there has been the following observation:
1. if I disable Dianoga.WebP.CDN, the webp functionality works properly.
2. if I enable Dianoga.WebP.CDN, again I do not see the webp files.

**Comment by markgibbons25** [comment]
It could be a conflict in the Sync / Async strategy. If you have Dianoga.WebP.CDN enabled then you need to disable Dianoga.Strategy.MediaCacheAsync.config.
