### ISSUE TITLE
svgop.exe does not accept the additional parameters

### ISSUE THREAD

**Issue by peng-qd** [kamsar/Dianoga#78]
### Version of Dianoga ###
5.0.1
### Environment description ###
Sitecore 8.2.7
### What configs you have enabled ###
Dianoga.DisableForSites.config
Dianoga.Jpeg.config
Dianoga.Png.config
Dianoga.Strategy.MediaCacheAsync.config
Dianoga.Svg.config (and GZip related has been commented out)
Dianoga.WebP.config
### Reproducible steps (1... 2... 3...) that cause the issue ###
Find a svg file that contains viewBox attribute, with default configuration, after optimization, the viewBox attribute is removed.
Now change the "AdditionalToolArguments" to --disable=removeViewBox, clear the mediacache folder, run the page, the viewBox attribute is still removed by Dianoga.
### What you expected to see, versus what you actually saw ###
If the "removeViewBox" plugin has been disabled via the "AdditionalToolArguments", the attribute should be kept.

**Comment by markgibbons25** [comment]
Thanks, fixed in 5.1.0
