### ISSUE TITLE
Encoded .svg files in media cache don't render appropriately on webpages

### ISSUE THREAD

**Issue by ericsteinmetz** [kamsar/Dianoga#79]
### Version of Dianoga ###
5.1.1
### Environment description ###
Sitecore 8.2.7
### What configs you have enabled ###
enable Dianoga.Svg.config
### Reproducible steps (1... 2... 3...) that cause the issue ###
upload .svg image
visit page with with uploaded image to store the image in the media cache
if asynchronous, ctrl + f5 to force refresh on the page to ensure if retrieves the file from the cache
am seeing a encoded .svg text and not an image
### What you expected to see, versus what you actually saw ###
not sure if I should expect a encoded .svg file or a typical .svg image with xml format in the media cache. If I should expect encoded .svg file, do I need extra logic to unencode the file before display on the webpage

I have included an example of a encoded .svg file
[103.zip](https://github.com/kamsar/Dianoga/files/5643442/103.zip)

Example of output
![2020-12-04_9-10-10](https://user-images.githubusercontent.com/43042613/101178896-88129900-3617-11eb-8ba9-94ea4dcf856d.png)

**Comment by markgibbons25** [comment]
What encoding is this? Looks like a binary?

**Comment by markgibbons25** [comment]
Closing from lack of info
