### ISSUE TITLE
[Feature] Ability to set path for temporary files

### ISSUE THREAD

**Issue by Antonytm** [kamsar/Dianoga#80]
It would nice to have the ability to set a temporary file path in the configuration of optimizers

For example, when this could be useful:
1. You are out of space on C: drive
2. But Dianoga (PngOptimizer) still tries to write files to C:\Windows\TEMP\. And it throws an error.
3. It is possible to override it by setting up an environment variable but in this case together with Dianoga temporary files, you will move other Windows temporary files
![image](https://user-images.githubusercontent.com/647813/102331864-0c5c0900-3f94-11eb-864b-986a9438f3d9.png)

Files, to be changed:
- CommandLineToolOptimizer.cs
- PngOptimizer.cs

Code that causing usage of temp system folder
```
Path.GetTempFileName()
```

**Comment by markgibbons25** [comment]
Added to 5.2.0
