### ISSUE TITLE
WebP image not getting generated in Sync scenario

### ISSUE THREAD

**Issue by AbhishekKumar26** [kamsar/Dianoga#84]
**Version of Dianoga**
5.0.1

**Environment description**
Sitecore 9.1 - Standalone

**What configs you have enabled**
Dianoga.DisableForSites.config
Dianoga.Jpeg.config
Dianoga.Png.config
Dianoga.WebP.CDN.config
Dianoga.WebP.Config
Dianoga.WebP.Response.Config

**Reproducible steps (1... 2... 3...) that cause the issue**
I have updated the media handler as mentioned in the documentation.
Images are getting optimized but .webp format is not getting generated. I checked inside the Media Cache.
Browser is sending the required attribute in the header.

In the media cache, webp image is not getting generated.

**What you expected to see, versus what you actually saw**
I am expecting webp image to be returned.

**Relevant logs**
No logs for Dianoga in the log file..

**Comment by markgibbons25** [comment]
If there's no logs then I don't think Dianoga is running. Also you should upgrade to 5.2.0 as it fixes some webp issues.

**Comment by markgibbons25** [comment]
Possibly there was a race condition here, please check again in 5.3.0
