### ISSUE TITLE
Webp is failing in case of CDN

### ISSUE THREAD

**Issue by AbhishekKumar26** [kamsar/Dianoga#85]
### Version of Dianoga ###
5.2
### Environment description ###
Azure PAAS
### What configs you have enabled ###
Dianoga.DisableForSites.config
Dianoga.Jpeg.config
Dianoga.Png.config
Dianoga.Strategy.GetMediaStreamSync.config
Dianoga.TempFilePath.config
Dianoga.WebP.config
### Reproducible steps (1... 2... 3...) that cause the issue ###
After deleting the media cache, browse the site and check for webp.

### Expected result ###
The image should be of webp.

### What I noticed ###
The webp is not getting generated.

**Comment by markgibbons25** [comment]
Please check the readme again , it has other steps for CDN support.
