### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by markgibbons25** [kamsar/Dianoga#89]
Who wants it? 
WIP branch: https://github.com/kamsar/Dianoga/tree/feature/avif
PR: #90 
Seeing some good gains over webp.

References: 
https://github.com/AOMediaCodec/libavif
https://caniuse.com/avif

**Comment by SudhirKumar2254** [comment]
@markgibbons25 - Do you need help on this issue ? If yes, could you please provide me more details . I am happy to help . :)

**Comment by markgibbons25** [comment]
I am thinking that we won't support AVIF as it seems that JPEG XL is going to be much better and more widely adopted https://caniuse.com/jpegxl . So for now I will leave this here incase of any other discussion but when JPEG XL is supported in Chrome we can add that.

@SudhirKumar2254 if you do want to help you could suggest some refactoring of how we can better support these plugins.

**Comment by SudhirKumar2254** [comment]
@markgibbons25 - Let's discuss and clear on what is expected here from me.  Thanks

**Comment by Antonytm** [comment]
Hi @markgibbons25 

I see your commit message: "Avif support. Only works on async mode at the moment, some issue with CDN sync mode."
Just for my curiosity, what issue do you have? (I checked CDN sync mode and it seems work fine after small change in `MediaRequestHandler` similar to `MediaRequestHandlerXA`)

**Comment by markgibbons25** [comment]
If it's working for you then I'm happy to merge a pr, ideally with some
refactoring to allow other modules such as when jpegxl gets adopted. Only
chrome supports avif though and it doesn't provide much benefit over
webp. if you can do regression testing too that would be appreciated. Needs
documentation etc. Thanks for looking into this.

**Comment by Antonytm** [comment]
Hi @markgibbons25 

There was done refactoring to allow easier enabling usage on new next-gen formats.
And I have added JPEG XL optimization to make sure that now it becomes easier.

Can you please take a look at this PR and let me know your thoughts?
https://github.com/kamsar/Dianoga/pull/100

**Comment by markgibbons25** [comment]
Many thanks, released in v6.
