### ISSUE TITLE
WebP possible with .ashx extensions disabled?

### ISSUE THREAD

**Issue by mattcdowning** [kamsar/Dianoga#97]
### Version of Dianoga ###
5.4.0
### Environment description ###
Sitecore 9.1.0
.NET Framework 4.7.1
### What configs you have enabled ###
Dianoga.Jpeg.config
Dianoga.Png.config
Dianoga.Strategy.MediaCacheAsync.config
Dianoga.Log.config
Dianoga.WebP.config
### Reproducible steps (1... 2... 3...) that cause the issue ###

- .ashx extension removed on media urls in Sitecore.config: `<setting name="Media.RequestExtension" value=""/>`
- MediaCache folder cleared.

### What you expected to see, versus what you actually saw ###
I've enabled WebP support per instructions in web.config:
`<add verb="*" path="sitecore_media.ashx" type="Dianoga.MediaRequestHandler, Dianoga" name="Sitecore.MediaRequestHandler" />`

Dianoga is successfully compressing images but not converting them to WebP format....should this conversion work even though I have .ashx extension disabled on media urls?

**Comment by markgibbons25** [comment]
Yes it should be working, I have tested with <setting name="Media.RequestExtension" value=""/>

**Comment by mattcdowning** [comment]
@markgibbons25 Thanks so much for confirming! I _**finally**_ got it working by going to the Properties of the file, Dianoga.WebP.config, in Visual Studio and changing Build Action from None to Content per this article: https://www.vinayjadav.com/posts/webp-for-sitecore-with-dianoga 🎉🎉🎉
