### ISSUE TITLE
Dianoga and image resizing

### ISSUE THREAD

**Issue by jimfranke** [kamsar/Dianoga#99]
Are the scaling parameters from Sitecore compatible with Dianoga? For example with the following url:
`/-/jssmedia/images/image.ashx?mh=400&mw=600`

Before adding Dianoga to the image pipeline this functionality was working as intended.
Can you please let me know if this feature is supported or what steps I have to take to get it working.

Thanks.

**Comment by markgibbons25** [comment]
Yes it's supported, I have tested it on a JSS + SXA site on sitecore 10.1.1. What is rendering that style URL though, I haven't seen that?
